"""
Demo item data — generated by Gemini for SwapHoot launch.
Edit this file to add/remove items, then re-run `python -m scripts.seed_demo_items`.
"""

DEMO_ITEMS = [
    {
        "owner_email": "oliver_smith_26@example.com",
        "title": "SAMPLE: Ryobi 18V Circular Saw (Tool Only)",
        "description": "Found this in the back of the shed during a cleanout. It has sawdust crusted on the baseplate and some scratches, but the motor runs fine. No battery included, just the tool.",
        "category": "Tools",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200",
        ],
    },
    {
        "owner_email": "oliver_smith_26@example.com",
        "title": "DEMO: Half-empty box of assorted wood screws",
        "description": "A heavy plastic tub full of random screws, nails, and a few washers. I consolidated my hardware and don't need these extras. Great for someone who just needs scrap hardware for odd jobs.",
        "category": "Tools",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1581147036324-c17440fd4c91?w=1200",
        ],
    },
    {
        "owner_email": "mia_wong_88@example.com",
        "title": "SAMPLE: Dusty 4-Person Coleman Tent",
        "description": "Hasn't been used since a camping trip three years ago. The bag is dusty and one of the tent pegs is slightly bent, but there are no tears in the canvas. Needs a good airing out in the yard.",
        "category": "Sports",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1537565266751-34dd699c27f3?w=1200",
        ],
    },
    {
        "owner_email": "mia_wong_88@example.com",
        "title": "DEMO: Vintage Esky / Hard Cooler",
        "description": "Classic blue hard cooler. It's got stickers on it from the 90s and some scuffs on the bottom from being dragged on concrete. Still keeps ice cold for a full weekend.",
        "category": "Other",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1596162954151-cdcb92b15db2?w=1200",
        ],
    },
    {
        "owner_email": "jack_thompson_v@example.com",
        "title": "SAMPLE: Old Wooden Step Ladder",
        "description": "Solid old timber ladder with paint splatters all over the steps. It's a bit heavy and creaks a little, but it's completely stable. Way better than those flimsy aluminum ones.",
        "category": "Garden",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1517409247385-2c8c4146ac91?w=1200",
        ],
    },
    {
        "owner_email": "chloe_davis_92@example.com",
        "title": "DEMO: Scratched Acoustic Guitar",
        "description": "I tried to learn during lockdown and gave up. It has a visible scratch on the front body from a belt buckle. Strings are probably dead and need replacing, but it plays.",
        "category": "Other",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1510915361894-faa8b2d18b6e?w=1200",
        ],
    },
    {
        "owner_email": "noah_wilson_oz@example.com",
        "title": "SAMPLE: Box of old RCA and HDMI Cables",
        "description": "A tangled cardboard box full of TV, audio, and random power cables I've hoarded for a decade. I know someone out there refuses to buy these new. Take the whole box.",
        "category": "Electronics",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=1200",
        ],
    },
    {
        "owner_email": "isla_brown_au@example.com",
        "title": "DEMO: Set of 3 Wobbly Bar Stools",
        "description": "Faux leather tops with metal legs. One of them is a bit wobbly and needs an allen key to tighten the base. There's a tiny tear in the fabric on the corner of another one.",
        "category": "Furniture",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1503602642458-232111445657?w=1200",
        ],
    },
    {
        "owner_email": "leo_knight_wa@example.com",
        "title": "SAMPLE: Hand-Me-Down Lawnmower",
        "description": "Petrol mower that takes a few hard pulls to start, but gets the job done. The grass catcher bag has a small hole taped up with duct tape. Giving it away because I moved to an apartment.",
        "category": "Garden",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1592424001925-50e50158a183?w=1200",
        ],
    },
    {
        "owner_email": "lars_eriksson_01@example.com",
        "title": "DEMO: Plastic Snow Shovel",
        "description": "Used for three winters. The metal strip on the plastic edge is slightly bent from hitting a curb, but it still clears the driveway perfectly fine. Just in time for the season.",
        "category": "Garden",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1516570161787-2faa7afdc007?w=1200",
        ],
    },
    {
        "owner_email": "freja_lind_sthlm@example.com",
        "title": "SAMPLE: Heavy Cast Iron Skillet (Needs Seasoning)",
        "description": "I accidentally left it wet in the sink and it developed some surface rust. It needs to be scrubbed with steel wool and re-seasoned in the oven. Heavy duty pan if you're willing to do the work.",
        "category": "Kitchen",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1588151146412-1f4a974b321c?w=1200",
        ],
    },
    {
        "owner_email": "sven_svensson_upp@example.com",
        "title": "DEMO: Bin of old Lego pieces",
        "description": "No original boxes or instructions, just a big plastic tub of random bricks, wheels, and half-built cars from when my sons were young. Probably 3-4 kg of plastic here.",
        "category": "Toys",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=1200",
        ],
    },
    {
        "owner_email": "ebba_nilsson_gbg@example.com",
        "title": "SAMPLE: IKEA Billy Bookcase (White)",
        "description": "The classic. It survived two apartment moves so the back cardboard panel is a bit loose and there are scuffs on the bottom shelf. Still stands straight. You will need a big car to move it.",
        "category": "Furniture",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=1200",
        ],
    },
    {
        "owner_email": "anders_berg_v@example.com",
        "title": "DEMO: Stained Work Jacket",
        "description": "Thick canvas winter work jacket. Extremely warm but it has permanent oil and paint stains on the sleeves from garage work. Zipper works perfectly. Good for messy outdoor jobs.",
        "category": "Clothing",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1549439602-43ebca2327af?w=1200",
        ],
    },
    {
        "owner_email": "malin_holm_m@example.com",
        "title": "SAMPLE: Vintage Bread Maker",
        "description": "Found this in my mom's attic. It's from the early 2000s, slightly yellowed plastic, but it still kneads and bakes. I don't have the paper manual but you can google the model number.",
        "category": "Kitchen",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200",
        ],
    },
    {
        "owner_email": "bjorn_skogs_02@example.com",
        "title": "DEMO: Box of random gardening tools",
        "description": "A rusty trowel, a hand rake with a loose wooden handle, and some dull pruning shears. I bought a new set so I'm getting rid of these. A little WD-40 will fix them right up.",
        "category": "Garden",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1416879598555-220bf21eb199?w=1200",
        ],
    },
    {
        "owner_email": "james_miller_nyc@example.com",
        "title": "SAMPLE: Flat Tire Bicycle (Fixer Upper)",
        "description": "Old steel-frame road bike. Both tires are completely flat and the chain is rusted orange. Frame is solid though. Needs a weekend of TLC to be rideable again.",
        "category": "Sports",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=1200",
        ],
    },
    {
        "owner_email": "sarah_jones_tx@example.com",
        "title": "DEMO: Unmatched Dumbbells (5lb and 10lb)",
        "description": "Lost the partners to these somewhere over the years. One is hex rubber, the other is cast iron. Good if you just want some heavy objects to lift while watching TV.",
        "category": "Sports",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=1200",
        ],
    },
    {
        "owner_email": "mike_davis_la@example.com",
        "title": "SAMPLE: Crate of Old Records",
        "description": "Mostly 70s rock and some classical stuff. The sleeves are water damaged from being in the basement, but the vinyl looks okay. Smell a little musty. Bring your own milk crate.",
        "category": "Other",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1483412033650-1015dce1591e?w=1200",
        ],
    },
    {
        "owner_email": "emma_white_se@example.com",
        "title": "DEMO: Old PC Monitor (VGA only)",
        "description": "Thick, heavy square monitor from 2008. It still turns on and the colors are fine. Only has a VGA port, no HDMI. Good for a retro gaming setup or a garage workbench screen.",
        "category": "Electronics",
        "condition": "good",
        "image_urls": [
            "https://images.unsplash.com/photo-1527443195645-1133f7f28990?w=1200",
        ],
    },
    {
        "owner_email": "robert_hall_chi@example.com",
        "title": "SAMPLE: Stack of DIY Home Improvement Books",
        "description": "About six thick books on plumbing, wiring, and deck building from before YouTube existed. Pages are dog-eared and some have greasy fingerprints. Still solid advice inside.",
        "category": "Books",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1200",
        ],
    },
    {
        "owner_email": "linda_clark_fl@example.com",
        "title": "DEMO: Scuffed up Wakeboard",
        "description": "Old wakeboard. The bottom is heavily scratched from hitting a ramp, and the bindings are starting to dry rot from the sun. Still floats and pulls fine behind a boat.",
        "category": "Sports",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1534098906915-11e0eecb57a8?w=1200",
        ],
    },
    {
        "owner_email": "david_lee_sf@example.com",
        "title": "SAMPLE: Partial roll of Chicken Wire",
        "description": "Maybe 10 feet left on this roll. Used it to patch a hole in my fence and it's been sitting in the corner of the yard since. A bit rusty on the edges.",
        "category": "Garden",
        "condition": "fair",
        "image_urls": [
            "https://images.unsplash.com/photo-1416879598555-220bf21eb199?w=1200",
        ],
    },
]
