"""
Seed demo users for launch.

Run from the `backend` folder with the venv active:
    python -m scripts.seed_demo_users

What it does:
  1. For each user in DEMO_USERS, skips if email or username already exists.
  2. Hashes the password using the same algorithm as the signup route.
  3. Geocodes the address via Nominatim (sleeps 1.1s between calls — be kind
     to the free service).
  4. Inserts the user with terms_accepted_at stamped to "now".
  5. Prints a summary.

Re-running is safe: existing demo users are skipped, not duplicated.
"""
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Make the backend package importable when run as `python -m scripts.seed_demo_users`
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from werkzeug.security import generate_password_hash

from app import create_app
from models import db, User
from services.geocoding import geocode_address, build_location_label


# ---------------------------------------------------------------------------
# Demo users — generated by Gemini for SwapHoot launch.
# Format: (email_local, username, password, country, city, street, postal_code, whatsapp)
# Email domain @example.com is appended below.
# ---------------------------------------------------------------------------
DEMO_USERS = [
    # AUSTRALIA
    ("oliver_smith_26", "oliver_smith_26", "Swap2026!Aus", "Australia", "Melbourne", "100 Collins St", "3000", "+61412345678"),
    ("mia_wong_88", "mia_wong_88", "Hoot2026!Safety", "Australia", "Melbourne", "250 Elizabeth St", "3000", "+61422334455"),
    ("jack_thompson_v", "jack_thompson_v", "Trade2026!Aussie", "Australia", "Sydney", "200 George St", "2000", "+61455667788"),
    ("chloe_davis_92", "chloe_davis_92", "Pass2026!Swap", "Australia", "Sydney", "50 Pitt St", "2000", "+61400112233"),
    ("noah_wilson_oz", "noah_wilson_oz", "Shed2026!Life", "Australia", "Brisbane", "150 Queen St", "4000", "+61499887766"),
    ("isla_brown_au", "isla_brown_au", "Green2026!Eco", "Australia", "Adelaide", "80 King William St", "5000", "+61433221100"),
    ("leo_knight_wa", "leo_knight_wa", "Perth2026!Swap", "Australia", "Perth", "215 St Georges Terrace", "6000", "+61477553311"),

    # SWEDEN
    ("lars_eriksson_01", "lars_eriksson_01", "Hej2026!Sverige", "Sweden", "Stockholm", "Drottninggatan 50", "111 21", "+46701112233"),
    ("freja_lind_sthlm", "freja_lind_sthlm", "Spara2026!Miljo", "Sweden", "Stockholm", "Sveavägen 42", "113 34", "+46731234567"),
    ("sven_svensson_upp", "sven_svensson_upp", "Uppsala2026!P", "Sweden", "Uppsala", "Kungsgatan 30", "753 21", "+46722233445"),
    ("ebba_nilsson_gbg", "ebba_nilsson_gbg", "Gbg2026!Trade", "Sweden", "Gothenburg", "Kungsportsavenyen 10", "411 36", "+46765554433"),
    ("anders_berg_v", "anders_berg_v", "Vasteras2026!", "Sweden", "Västerås", "Stora Gatan 25", "722 12", "+46798887766"),
    ("malin_holm_m", "malin_holm_m", "Malmo2026!Eco", "Sweden", "Malmö", "Södergatan 15", "211 34", "+46700001122"),
    ("bjorn_skogs_02", "bjorn_skogs_02", "Skog2026!Swap", "Sweden", "Stockholm", "Hamngatan 18", "111 47", "+46733334455"),

    # USA
    ("james_miller_nyc", "james_miller_nyc", "BigApple2026!", "United States", "New York", "729 7th Ave", "10019", "+12125550199"),
    ("sarah_jones_tx", "sarah_jones_tx", "Austin2026!Swap", "United States", "Austin", "1100 Congress Ave", "78701", "+15125550188"),
    ("mike_davis_la", "mike_davis_la", "Sunset2026!Hoot", "United States", "Los Angeles", "8400 Sunset Blvd", "90069", "+13235550177"),
    ("emma_white_se", "emma_white_se", "Seattle2026!Rain", "United States", "Seattle", "1501 Pike Pl", "98101", "+12065550166"),
    ("robert_hall_chi", "robert_hall_chi", "Chicago2026!Wind", "United States", "Chicago", "401 N Michigan Ave", "60611", "+13125550155"),
    ("linda_clark_fl", "linda_clark_fl", "Miami2026!Sun", "United States", "Miami", "401 Biscayne Blvd", "33132", "+13055550144"),
    ("david_lee_sf", "david_lee_sf", "GoldenGate2026!", "United States", "San Francisco", "1 Ferry Building", "94111", "+14155550133"),
]

GEOCODE_DELAY_SECONDS = 1.1  # Nominatim asks for max 1 req/sec


def seed():
    app = create_app()
    with app.app_context():
        created = 0
        skipped = 0
        geocode_failed = 0

        for i, row in enumerate(DEMO_USERS, start=1):
            (
                email_local,
                username,
                password,
                country,
                city,
                street,
                postal_code,
                whatsapp,
            ) = row
            email = f"{email_local}@example.com"

            # Skip duplicates
            if User.query.filter(
                (User.email == email) | (User.username == username)
            ).first():
                print(f"[{i:02d}] SKIP    {email} (already exists)")
                skipped += 1
                continue

            # Geocode — sleep first (except for the first request) to respect Nominatim
            if created > 0:
                time.sleep(GEOCODE_DELAY_SECONDS)
            lat, lng = geocode_address(
                country=country, city=city, street=street, postal_code=postal_code
            )
            if lat is None:
                print(f"[{i:02d}] WARN    {email} — geocoding failed; will not appear in nearby search")
                geocode_failed += 1

            user = User(
                email=email,
                username=username,
                password_hash=generate_password_hash(password),
                country=country,
                city=city,
                street=street,
                postal_code=postal_code,
                location=build_location_label(city, country),
                latitude=lat,
                longitude=lng,
                whatsapp=whatsapp,
                email_notifications=True,
                terms_accepted_at=datetime.now(timezone.utc),
            )
            db.session.add(user)
            db.session.commit()
            created += 1
            print(f"[{i:02d}] CREATED {email}  ({city}, {country})  lat={lat} lng={lng}")

        print()
        print(f"Done.  created={created}  skipped={skipped}  geocode_failed={geocode_failed}")


if __name__ == "__main__":
    seed()
